require('dotenv').config();
const mongoose = require('mongoose');
const Spot = require('../models/Spot');
const User = require('../models/User');

// Vijayawada Eco Locations - 53 spots
const vijayawadaSpots = [
    // 1-5: Major Attractions
    {
        name: 'Bhavani Island',
        category: 'nature',
        address: 'Krishna River, Punnami Ghat, Krishnalanka, Vijayawada – 520013',
        lat: 16.5062,
        lng: 80.61199999999999,
        cost: '₹20 (boat extra)',
        opening_hours: '9:00 AM – 6:00 PM',
        tips: ['Largest river island in AP', 'Accessible by boat from Punnami Ghat', 'Resort stay available on island', 'Best in Oct–Feb'],
    },
    {
        name: 'Rajiv Gandhi Park',
        category: 'park',
        address: 'NH 65, Krishnalanka, Vijayawada – 520013',
        lat: 16.5081,
        lng: 80.6198,
        cost: '₹20',
        opening_hours: '6:00 AM – 9:00 PM',
        tips: ['Riverside green lung', 'Musical fountain', 'Mini zoo and dinosaur park', 'Well-maintained lawns'],
    },
    {
        name: 'Kondapalli Reserve Forest',
        category: 'nature',
        address: 'Kondapalli Hills, Krishna District – 521228',
        lat: 16.6167,
        lng: 80.5333,
        cost: 'Free',
        opening_hours: 'Sunrise – Sunset',
        tips: ['Dense mixed-deciduous forest', 'Wildlife corridor', 'Kondapalli Fort within forest', 'Home to toy artisans nearby'],
    },
    {
        name: 'Mangalagiri Hills & Reserve Forest',
        category: 'nature',
        address: 'Mangalagiri, Guntur District – 522503',
        lat: 16.43,
        lng: 80.55800000000001,
        cost: 'Free (temple ₹20)',
        opening_hours: '5:00 AM – 9:00 PM',
        tips: ['Sacred hill with dry scrub forest', 'Important bird area', 'Ancient Narasimha Swamy temple at top'],
    },
    {
        name: 'Undavalli Caves & Greenery',
        category: 'nature',
        address: 'Undavalli, Guntur District – 522501',
        lat: 16.5151,
        lng: 80.6002,
        cost: '₹25',
        opening_hours: '9:00 AM – 5:30 PM',
        tips: ['Ancient rock-cut caves', 'Banyan and fig trees', 'Scenic Krishna river view', 'Combine with boat ride to Prakasam Barrage'],
    },
    // 6-10
    {
        name: 'Prakasam Barrage & Riverside',
        category: 'park',
        address: 'Prakasam Barrage Rd, Vijayawada – 520002',
        lat: 16.5069,
        lng: 80.5962,
        cost: 'Free',
        opening_hours: 'Open 24 hours',
        tips: ['Krishna riverfront with barrage wetlands', 'Migratory birds', 'Best at sunset', 'Watch fish ladders and water release'],
    },
    {
        name: 'Gandhi Hill',
        category: 'park',
        address: 'Gandhi Hill Rd, Vijayawada – 520010',
        lat: 16.5097,
        lng: 80.636,
        cost: '₹10',
        opening_hours: '5:00 AM – 8:00 PM',
        tips: ['7 hillocks with landscaped gardens', 'Observatory', 'Accessible by ropeway', 'Excellent panoramic city and river views'],
    },
    {
        name: 'Mogalarajapuram Caves Park',
        category: 'park',
        address: 'Mogalarajapuram, Vijayawada – 520010',
        lat: 16.5064,
        lng: 80.6544,
        cost: 'Free',
        opening_hours: '6:00 AM – 7:00 PM',
        tips: ['Rock-cut temple complex with tree cover', 'Bats and birds', 'Ancient Shiva temple caves', 'Quiet green enclave'],
    },
    {
        name: 'Raghavaiah Park',
        category: 'park',
        address: 'near Bandar Canal, Vijayawada – 520010',
        lat: 16.5085,
        lng: 80.6412,
        cost: 'Free',
        opening_hours: '5:30 AM – 9:00 PM',
        tips: ['Canal-side park with tall trees', 'Urban biodiversity', 'Popular among local walkers'],
    },
    {
        name: 'Prakasam Park',
        category: 'park',
        address: 'Besant Rd, Vijayawada – 520002',
        lat: 16.5068,
        lng: 80.6427,
        cost: 'Free',
        opening_hours: '5:00 AM – 10:00 PM',
        tips: ['Shaded tree canopy', 'Ornamental shrubs', 'Small green refuge in dense city'],
    },
    // 11-15
    {
        name: 'Andhra Ratna Municipal Park',
        category: 'park',
        address: 'Municipal Office Rd, Vijayawada – 520001',
        lat: 16.5182,
        lng: 80.6094,
        cost: 'Free',
        opening_hours: '6:00 AM – 8:00 PM',
        tips: ['Landscaped lawns', 'Flowering hedges', 'Mature shade trees'],
    },
    {
        name: 'KL Rao Park',
        category: 'park',
        address: 'KL Rao Rd, Vijayawada – 520010',
        lat: 16.5005,
        lng: 80.6421,
        cost: '₹10',
        opening_hours: '6:00 AM – 9:00 PM',
        tips: ['Large urban park with lawns', 'Children\'s play area', 'Shaded walking tracks', 'Well-maintained'],
    },
    {
        name: 'Alluri Sitaramaraju Park',
        category: 'park',
        address: 'Bandar Canal bund, Vijayawada – 520008',
        lat: 16.5059,
        lng: 80.6395,
        cost: 'Free',
        opening_hours: '5:30 AM – 9:00 PM',
        tips: ['Tree-lined canal bund', 'Birds and butterflies', 'Good breeze and shade'],
    },
    {
        name: 'Veterinary Colony Park',
        category: 'park',
        address: 'Veterinary Colony, Vijayawada – 520008',
        lat: 16.4983,
        lng: 80.6259,
        cost: 'Free',
        opening_hours: '6:00 AM – 8:30 PM',
        tips: ['Community green space', 'Low-key local park', 'Calm residential setting'],
    },
    {
        name: 'Scrap Metal Sculpture Park',
        category: 'park',
        address: 'Auto Nagar Rd, Vijayawada – 520007',
        lat: 16.4844,
        lng: 80.6698,
        cost: 'Free',
        opening_hours: '10:00 AM – 6:00 PM',
        tips: ['Upcycled metal art', 'Educational eco-installations', 'Good for awareness programs'],
    },
    // 16-20: Major Wetland/Wildlife Sites
    {
        name: 'Kolleru Lake Bird Sanctuary',
        category: 'nature',
        address: 'Kolleru Lake, Eluru District – 534112',
        lat: 16.6592,
        lng: 81.2222,
        cost: '₹50',
        opening_hours: '6:00 AM – 6:00 PM',
        tips: ['One of Asia\'s largest freshwater lakes', 'Migratory birds', 'Huge biodiversity hotspot', 'Best during winter migration'],
    },
    {
        name: 'Kondapalli Fort Hilltop',
        category: 'nature',
        address: 'Kondapalli Fort Rd, Krishna District – 521228',
        lat: 16.6199,
        lng: 80.5356,
        cost: 'Free',
        opening_hours: 'Sunrise – Sunset',
        tips: ['Hill fortress surrounded by scrub forest', 'Panoramic terrain', 'Combine with toys village and reserve forest'],
    },
    {
        name: 'Akkana Madanna Caves',
        category: 'park',
        address: 'near Durga Agraharam, Vijayawada – 520002',
        lat: 16.5051,
        lng: 80.6109,
        cost: 'Free',
        opening_hours: '9:00 AM – 6:00 PM',
        tips: ['Ancient cave structures', 'Trees and quiet garden', 'Small but significant historical eco-heritage site'],
    },
    {
        name: 'Indrakeeladri Hilltop Walk',
        category: 'nature',
        address: 'Kanaka Durga Temple Rd, Vijayawada – 520001',
        lat: 16.5084,
        lng: 80.6008,
        cost: 'Free (temple may charge some services)',
        opening_hours: '4:00 AM – 10:00 PM',
        tips: ['Hill ecology with dry deciduous vegetation', 'Ropeway available', 'Great early morning climb', 'Iconic hill above city'],
    },
    {
        name: 'Punnami Ghat Riverside Walk',
        category: 'park',
        address: 'near Krishna river, Vijayawada – 520013',
        lat: 16.506,
        lng: 80.6135,
        cost: 'Free',
        opening_hours: 'Open 24 hours',
        tips: ['Riverfront promenade', 'Wetland birds', 'Popular for sunset', 'Boat rides to Bhavani Island'],
    },
    // 21-25
    {
        name: 'Atapaka Bird Sanctuary (Kolleru)',
        category: 'nature',
        address: 'Atapaka village, Krishna District – 521148',
        lat: 16.7108,
        lng: 81.2027,
        cost: '₹20',
        opening_hours: '6:00 AM – 5:30 PM',
        tips: ['Spotted pelicans and painted storks', 'Open wetland marshes', 'Wooden watch towers', 'Ideal for winter bird migration'],
    },
    {
        name: 'Alapadu Freshwater Wetland',
        category: 'nature',
        address: 'Alapadu, Krishna District – 521207',
        lat: 16.7783,
        lng: 80.9005,
        cost: 'Free',
        opening_hours: 'Sunrise – Sunset',
        tips: ['Freshwater fields and reeds', 'Water birds', 'Quiet eco-spot with rural landscape'],
    },
    {
        name: 'Dharanikota Ancient Stupa Zone',
        category: 'park',
        address: 'Dharanikota, Guntur District – 522020',
        lat: 16.5731,
        lng: 80.3579,
        cost: '₹20',
        opening_hours: '9:00 AM – 5:00 PM',
        tips: ['Ancient Buddhist landscape', 'River plains and dry scrub', 'Part of Amaravati heritage belt'],
    },
    {
        name: 'Amaravati Stupa & Museum',
        category: 'park',
        address: 'Amaravati, Guntur District – 522020',
        lat: 16.5744,
        lng: 80.3571,
        cost: '₹25',
        opening_hours: '9:00 AM – 5:30 PM',
        tips: ['Buddhist monument with landscaped lawns', 'Adjacent to riverine ecology', 'Important cultural site'],
    },
    {
        name: 'Dhyana Buddha Park',
        category: 'park',
        address: 'Dhyana Buddha Rd, Amaravati – 522020',
        lat: 16.5715,
        lng: 80.3632,
        cost: '₹20',
        opening_hours: '9:00 AM – 8:00 PM',
        tips: ['Large Buddha statue', 'Gardens and water features', 'Peaceful manicured site', 'Good for sunset'],
    },
    // 26-30
    {
        name: 'Undavalli Ghat Nature Walk',
        category: 'park',
        address: 'Krishna riverbank near Undavalli, Guntur District – 522501',
        lat: 16.5145,
        lng: 80.5989,
        cost: 'Free',
        opening_hours: '6:00 AM – 7:00 PM',
        tips: ['Riverbank vegetation and birds', 'Boat access', 'Can link with caves and Prakasam Barrage by boat'],
    },
    {
        name: 'Pedda Avutapalli Wetland',
        category: 'nature',
        address: 'Pedda Avutapalli, NTR District – 521286',
        lat: 16.6833,
        lng: 80.8167,
        cost: 'Free',
        opening_hours: 'Sunrise – Sunset',
        tips: ['Seasonal wetland and reeds', 'Local migratory birds', 'Best after monsoon'],
    },
    {
        name: 'Mallavalli Mango Orchards',
        category: 'nature',
        address: 'Mallavalli, Krishna District – 521162',
        lat: 16.5521,
        lng: 80.9674,
        cost: 'Free (farm access varies)',
        opening_hours: 'Seasonal / Daylight',
        tips: ['Mango orchards and pollinators', 'Rural farm biodiversity', 'Best during flowering and fruit season'],
    },
    {
        name: 'Kondapalli Hills View Point',
        category: 'park',
        address: 'Kondapalli Hills viewpoint, Krishna District – 521228',
        lat: 16.6138,
        lng: 80.5298,
        cost: 'Free',
        opening_hours: 'Sunrise – Sunset',
        tips: ['Dry hill ecology', 'Native shrubs and bird activity', 'Excellent overlook of Vijayawada plains'],
    },
    {
        name: 'Bandar Canal Biodiversity Strip',
        category: 'park',
        address: 'Bandar Canal, Vijayawada – 520010',
        lat: 16.5041,
        lng: 80.6473,
        cost: 'Free',
        opening_hours: 'Open 24 hours',
        tips: ['Canal-side trees and birds', 'Butterflies and linear habitat', 'Important urban ecological corridor'],
    },
    {
        name: 'Krishna Barrage Walkway',
        category: 'park',
        address: 'Prakasam Barrage bridge side, Vijayawada – 520013',
        lat: 16.5072,
        lng: 80.5969,
        cost: 'Free',
        opening_hours: 'Open 24 hours',
        tips: ['River flow view and wetland birds', 'Connects to riverfront parks', 'Good after dusk'],
    },
    // 31-35
    {
        name: 'Devarkonda Hillocks',
        category: 'nature',
        address: 'Devarkonda, Guntur District – 522034',
        lat: 16.3912,
        lng: 80.4957,
        cost: 'Free',
        opening_hours: 'Sunrise – Sunset',
        tips: ['Rocky hillocks with scrub vegetation', 'Remote natural escape', 'Sparse crowds'],
    },
    {
        name: 'Kanaka Durga Temple Forest Belt',
        category: 'nature',
        address: 'Kanaka Durga Temple complex, Vijayawada – 520001',
        lat: 16.5091,
        lng: 80.6004,
        cost: 'Free (except services)',
        opening_hours: '4:00 AM – 10:00 PM',
        tips: ['Temple grove with hill trees', 'Birds and bats', 'Religious and ecological significance'],
    },
    {
        name: 'Amaravati Riverine Plains',
        category: 'nature',
        address: 'Amaravati, Guntur District – 522020',
        lat: 16.5794,
        lng: 80.3698,
        cost: 'Free',
        opening_hours: 'Daylight hours',
        tips: ['Paddy fields and river floodplain', 'Seasonal wetlands', 'Great for landscape ecology study'],
    },
    {
        name: 'Thotlavalluru Wetlands',
        category: 'nature',
        address: 'Thotlavalluru, Krishna District – 521163',
        lat: 16.5538,
        lng: 80.8444,
        cost: 'Free',
        opening_hours: 'Sunrise – Sunset',
        tips: ['Marshy fields and reeds', 'Waterfowl and amphibian habitat', 'Seasonal wetland near Krishna river'],
    },
    {
        name: 'Chandarlapadu Reservoir Edge',
        category: 'nature',
        address: 'Chandarlapadu, NTR District – 521182',
        lat: 16.7675,
        lng: 80.3091,
        cost: 'Free',
        opening_hours: 'Daylight hours',
        tips: ['Reservoir edge habitat', 'Fish and birds', 'Quiet rural waterbody with ecological value'],
    },
    // 36-40
    {
        name: 'Mylavaram Forest Fringes',
        category: 'nature',
        address: 'Mylavaram, Krishna District – 521230',
        lat: 16.7681,
        lng: 80.6065,
        cost: 'Free',
        opening_hours: 'Sunrise – Sunset',
        tips: ['Forest edge with dry deciduous species', 'Birds and butterflies', 'Good monsoon greenery'],
    },
    {
        name: 'Nunna Village Tank',
        category: 'nature',
        address: 'Nunna, Krishna District – 521212',
        lat: 16.6502,
        lng: 80.6841,
        cost: 'Free',
        opening_hours: 'Sunrise – Sunset',
        tips: ['Village tank with aquatic plants', 'Herons, egrets, and reeds', 'Good for local biodiversity'],
    },
    {
        name: 'Tadepalli Krishna Riverbank',
        category: 'park',
        address: 'Tadepalli, Guntur District – 522501',
        lat: 16.4849,
        lng: 80.6057,
        cost: 'Free',
        opening_hours: 'Open 24 hours',
        tips: ['Riverbank trees and birds', 'Accessible city-side riverfront', 'Calm atmosphere'],
    },
    {
        name: 'Velagaleru Wet Fields',
        category: 'nature',
        address: 'Velagaleru, Krishna District – 521181',
        lat: 16.6034,
        lng: 80.7592,
        cost: 'Free',
        opening_hours: 'Daylight hours',
        tips: ['Waterlogged paddy fields', 'Birds and frogs', 'Best in monsoon and early winter'],
    },
    {
        name: 'Ramalingeswara Nagar Park',
        category: 'park',
        address: 'Ramalingeswara Nagar, Vijayawada – 520013',
        lat: 16.4937,
        lng: 80.6415,
        cost: 'Free',
        opening_hours: '6:00 AM – 9:00 PM',
        tips: ['Community trees and lawns', 'Walking track', 'Neighborhood park with decent shade'],
    },
    // 41-45
    {
        name: 'Patamata Lake Edge',
        category: 'park',
        address: 'Patamata, Vijayawada – 520010',
        lat: 16.5048,
        lng: 80.6674,
        cost: 'Free',
        opening_hours: '6:00 AM – 8:00 PM',
        tips: ['Urban waterbody with reeds', 'Ducks and seasonal birds', 'Small but useful urban wetland pocket'],
    },
    {
        name: 'Gollapudi Green Belt',
        category: 'park',
        address: 'Gollapudi, Vijayawada – 521225',
        lat: 16.5163,
        lng: 80.7148,
        cost: 'Free',
        opening_hours: 'Daylight hours',
        tips: ['Peripheral green belt', 'Native shrubs and birds', 'Transition zone from city to countryside'],
    },
    {
        name: 'Undavalli Quarry Green Patch',
        category: 'park',
        address: 'near Undavalli, Guntur District – 522501',
        lat: 16.5169,
        lng: 80.5944,
        cost: 'Free',
        opening_hours: 'Daylight hours',
        tips: ['Reclaimed quarry with shrubs', 'Grasses and birds', 'Interesting example of landscape recovery'],
    },
    {
        name: 'Krishna River Island Sandbars',
        category: 'nature',
        address: 'Near Vijayawada river reach',
        lat: 16.509,
        lng: 80.605,
        cost: 'Free',
        opening_hours: 'Sunrise – Sunset',
        tips: ['Seasonal sandbars', 'River birds and aquatic edge', 'Safety varies with water level'],
    },
    {
        name: 'Pedavutapalli Coconut Groves',
        category: 'nature',
        address: 'Pedavutapalli, Krishna District – 521228',
        lat: 16.6902,
        lng: 80.7791,
        cost: 'Free',
        opening_hours: 'Daylight hours',
        tips: ['Coconut plantations with shade', 'Pollinators and rural biodiversity', 'Typical peri-urban agri-ecology site'],
    },
    // 46-50
    {
        name: 'Penumaka Wetlands',
        category: 'nature',
        address: 'Penumaka, Guntur District – 522501',
        lat: 16.4828,
        lng: 80.5961,
        cost: 'Free',
        opening_hours: 'Sunrise – Sunset',
        tips: ['Shallow wetland and reeds', 'Ducks and waders', 'Part of Krishna floodplain ecology'],
    },
    {
        name: 'Katrapadu Open Scrub Land',
        category: 'nature',
        address: 'Katrapadu, Krishna District – 521211',
        lat: 16.6025,
        lng: 80.7228,
        cost: 'Free',
        opening_hours: 'Daylight hours',
        tips: ['Dry scrub and grasses', 'Lizards and butterflies', 'Open natural patch close to suburbs'],
    },
    {
        name: 'Mylavaram Reservoir (Pullichintala)',
        category: 'nature',
        address: 'Pullichintala Project, Mylavaram – 521230',
        lat: 16.7885,
        lng: 80.6421,
        cost: 'Free',
        opening_hours: 'Sunrise – Sunset',
        tips: ['Large Krishna reservoir', 'Migratory waterfowl', 'Crocodile sightings reported', 'Excellent winter birding'],
    },
    {
        name: 'Uppalapadu Bird Sanctuary',
        category: 'nature',
        address: 'Uppalapadu, Guntur District – 522017',
        lat: 16.2902,
        lng: 80.3874,
        cost: '₹20',
        opening_hours: '6:00 AM – 6:00 PM',
        tips: ['Only inland pelican nesting colony in India', 'Globally significant', 'Conservation education', 'Must-visit for birders'],
    },
    {
        name: 'Krishna Wildlife Sanctuary (Mangroves)',
        category: 'nature',
        address: 'Krishna Wildlife Sanctuary, Diviseema',
        lat: 16.2589,
        lng: 81.1253,
        cost: '₹50',
        opening_hours: '6:00 AM – 5:00 PM',
        tips: ['Mangrove ecosystem', 'Sea turtle nesting', 'Irrawaddy dolphins', 'Important Ramsar-listed wetland'],
    },
    // 51-53
    {
        name: 'Amaravati Eco Tourism Circuit',
        category: 'park',
        address: 'Amaravati to Undavalli eco circuit, Guntur Dist',
        lat: 16.565,
        lng: 80.371,
        cost: 'Varies',
        opening_hours: 'Full day',
        tips: ['Combined river, heritage & agricultural landscape', 'Krishna floodplain', 'Covers Amaravati stupa, Dhyana Buddha, river cruise'],
    },
];

async function seedDatabase() {
    try {
        await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/ecosaathi');
        console.log('✅ Connected to MongoDB');

        // Get or create a default admin user for seeding
        let adminUser = await User.findOne({ phone: '9999999998' });
        if (!adminUser) {
            adminUser = await User.create({
                name: 'Vijayawada Admin',
                phone: '9999999998',
                password: 'admin123',
                city: 'Vijayawada',
            });
            console.log('✅ Created Vijayawada admin user for seeding');
        }

        // Insert seed spots with Vijayawada city tag
        const spotsWithUser = vijayawadaSpots.map((spot) => ({
            ...spot,
            city: 'Vijayawada', // Ensure all spots are tagged as Vijayawada
            added_by: adminUser._id,
            verified_by: [], // Allow users to verify
        }));

        const insertedSpots = await Spot.insertMany(spotsWithUser);
        console.log(`✅ Seeded ${insertedSpots.length} Vijayawada eco locations`);

        await mongoose.connection.close();
        console.log('✅ Database connection closed');
    } catch (error) {
        console.error('❌ Seeding failed:', error.message);
        process.exit(1);
    }
}

seedDatabase();
